name: Build

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - '*.*.*'
    tags:
      - '*.*.*.*'

jobs:
  wrapper-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

  build:
    needs: wrapper-validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew build

  dependency-submission:
    needs: wrapper-validation
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v6
